/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sport = IDL.Variant({
  'baseball' : IDL.Null,
  'softball' : IDL.Null,
});
export const EquipmentCategory = IDL.Variant({
  'bat' : IDL.Null,
  'tee' : IDL.Null,
  'helmet' : IDL.Null,
  'chestPlate' : IDL.Null,
  'baseball' : IDL.Null,
  'catchersHelmet' : IDL.Null,
  'other' : IDL.Null,
  'shinGuards' : IDL.Null,
  'softball' : IDL.Null,
  'catchersGlove' : IDL.Null,
  'glove' : IDL.Null,
  'equipmentBag' : IDL.Null,
});
export const EquipmentCondition = IDL.Variant({
  'damaged' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
});
export const EquipmentItem = IDL.Record({
  'id' : IDL.Nat,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'sport' : Sport,
  'notes' : IDL.Text,
  'category' : EquipmentCategory,
  'totalQuantity' : IDL.Nat,
  'condition' : EquipmentCondition,
});
export const RecipientType = IDL.Variant({
  'coach' : IDL.Null,
  'team' : IDL.Null,
});
export const Issuance = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : IDL.Int,
  'quantityIssued' : IDL.Nat,
  'recipientPhone' : IDL.Text,
  'isReturned' : IDL.Bool,
  'returnCondition' : IDL.Opt(EquipmentCondition),
  'notes' : IDL.Text,
  'equipmentItemId' : IDL.Nat,
  'recipientName' : IDL.Text,
  'recipientType' : RecipientType,
  'returnDate' : IDL.Opt(IDL.Int),
  'recipientEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEquipmentItem' : IDL.Func([EquipmentItem], [EquipmentItem], []),
  'createIssuance' : IDL.Func([Issuance], [Issuance], []),
  'deleteEquipmentItem' : IDL.Func([IDL.Nat], [], []),
  'getActiveIssuances' : IDL.Func([], [IDL.Vec(Issuance)], ['query']),
  'getAllEquipmentItems' : IDL.Func(
      [IDL.Opt(Sport)],
      [IDL.Vec(EquipmentItem)],
      ['query'],
    ),
  'getEquipmentItem' : IDL.Func([IDL.Nat], [EquipmentItem], ['query']),
  'getIssuanceHistoryForItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Issuance)],
      ['query'],
    ),
  'getIssuancesByRecipient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Issuance)],
      ['query'],
    ),
  'markAsReturned' : IDL.Func([IDL.Nat, EquipmentCondition], [Issuance], []),
  'updateEquipmentItem' : IDL.Func(
      [IDL.Nat, EquipmentItem],
      [EquipmentItem],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sport = IDL.Variant({ 'baseball' : IDL.Null, 'softball' : IDL.Null });
  const EquipmentCategory = IDL.Variant({
    'bat' : IDL.Null,
    'tee' : IDL.Null,
    'helmet' : IDL.Null,
    'chestPlate' : IDL.Null,
    'baseball' : IDL.Null,
    'catchersHelmet' : IDL.Null,
    'other' : IDL.Null,
    'shinGuards' : IDL.Null,
    'softball' : IDL.Null,
    'catchersGlove' : IDL.Null,
    'glove' : IDL.Null,
    'equipmentBag' : IDL.Null,
  });
  const EquipmentCondition = IDL.Variant({
    'damaged' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
  });
  const EquipmentItem = IDL.Record({
    'id' : IDL.Nat,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'sport' : Sport,
    'notes' : IDL.Text,
    'category' : EquipmentCategory,
    'totalQuantity' : IDL.Nat,
    'condition' : EquipmentCondition,
  });
  const RecipientType = IDL.Variant({ 'coach' : IDL.Null, 'team' : IDL.Null });
  const Issuance = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : IDL.Int,
    'quantityIssued' : IDL.Nat,
    'recipientPhone' : IDL.Text,
    'isReturned' : IDL.Bool,
    'returnCondition' : IDL.Opt(EquipmentCondition),
    'notes' : IDL.Text,
    'equipmentItemId' : IDL.Nat,
    'recipientName' : IDL.Text,
    'recipientType' : RecipientType,
    'returnDate' : IDL.Opt(IDL.Int),
    'recipientEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'addEquipmentItem' : IDL.Func([EquipmentItem], [EquipmentItem], []),
    'createIssuance' : IDL.Func([Issuance], [Issuance], []),
    'deleteEquipmentItem' : IDL.Func([IDL.Nat], [], []),
    'getActiveIssuances' : IDL.Func([], [IDL.Vec(Issuance)], ['query']),
    'getAllEquipmentItems' : IDL.Func(
        [IDL.Opt(Sport)],
        [IDL.Vec(EquipmentItem)],
        ['query'],
      ),
    'getEquipmentItem' : IDL.Func([IDL.Nat], [EquipmentItem], ['query']),
    'getIssuanceHistoryForItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Issuance)],
        ['query'],
      ),
    'getIssuancesByRecipient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Issuance)],
        ['query'],
      ),
    'markAsReturned' : IDL.Func([IDL.Nat, EquipmentCondition], [Issuance], []),
    'updateEquipmentItem' : IDL.Func(
        [IDL.Nat, EquipmentItem],
        [EquipmentItem],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };