/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EquipmentCategory = { 'bat' : null } |
  { 'tee' : null } |
  { 'helmet' : null } |
  { 'chestPlate' : null } |
  { 'baseball' : null } |
  { 'catchersHelmet' : null } |
  { 'other' : null } |
  { 'shinGuards' : null } |
  { 'softball' : null } |
  { 'catchersGlove' : null } |
  { 'glove' : null } |
  { 'equipmentBag' : null };
export type EquipmentCondition = { 'damaged' : null } |
  { 'fair' : null } |
  { 'good' : null };
export interface EquipmentItem {
  'id' : bigint,
  'availableQuantity' : bigint,
  'name' : string,
  'sport' : Sport,
  'notes' : string,
  'category' : EquipmentCategory,
  'totalQuantity' : bigint,
  'condition' : EquipmentCondition,
}
export interface Issuance {
  'id' : bigint,
  'issueDate' : bigint,
  'quantityIssued' : bigint,
  'recipientPhone' : string,
  'isReturned' : boolean,
  'returnCondition' : [] | [EquipmentCondition],
  'notes' : string,
  'equipmentItemId' : bigint,
  'recipientName' : string,
  'recipientType' : RecipientType,
  'returnDate' : [] | [bigint],
  'recipientEmail' : string,
}
export type RecipientType = { 'coach' : null } |
  { 'team' : null };
export type Sport = { 'baseball' : null } |
  { 'softball' : null };
export interface User {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEquipmentItem' : ActorMethod<[EquipmentItem], EquipmentItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createIssuance' : ActorMethod<[Issuance], Issuance>,
  'deleteEquipmentItem' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[bigint], undefined>,
  'getActiveIssuances' : ActorMethod<[], Array<Issuance>>,
  'getAllEquipmentItems' : ActorMethod<[[] | [Sport]], Array<EquipmentItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEquipmentItem' : ActorMethod<[bigint], EquipmentItem>,
  'getIssuanceHistoryForItem' : ActorMethod<[bigint], Array<Issuance>>,
  'getIssuancesByRecipient' : ActorMethod<[string], Array<Issuance>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'markAsReturned' : ActorMethod<[bigint, EquipmentCondition], Issuance>,
  'registerUser' : ActorMethod<
    [string, string, string],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEquipmentItem' : ActorMethod<[bigint, EquipmentItem], EquipmentItem>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];