/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EquipmentItem {
    id: bigint;
    availableQuantity: bigint;
    name: string;
    sport: Sport;
    notes: string;
    category: EquipmentCategory;
    totalQuantity: bigint;
    condition: EquipmentCondition;
}
export interface User {
    id: bigint;
    name: string;
    email: string;
    passwordHash: string;
}
export interface Issuance {
    id: bigint;
    issueDate: bigint;
    quantityIssued: bigint;
    recipientPhone: string;
    isReturned: boolean;
    returnCondition?: EquipmentCondition;
    notes: string;
    equipmentItemId: bigint;
    recipientName: string;
    recipientType: RecipientType;
    returnDate?: bigint;
    recipientEmail: string;
}
export interface UserProfile {
    name: string;
}
export enum EquipmentCategory {
    bat = "bat",
    tee = "tee",
    helmet = "helmet",
    chestPlate = "chestPlate",
    baseball = "baseball",
    catchersHelmet = "catchersHelmet",
    other = "other",
    shinGuards = "shinGuards",
    softball = "softball",
    catchersGlove = "catchersGlove",
    glove = "glove",
    equipmentBag = "equipmentBag"
}
export enum EquipmentCondition {
    damaged = "damaged",
    fair = "fair",
    good = "good"
}
export enum RecipientType {
    coach = "coach",
    team = "team"
}
export enum Sport {
    baseball = "baseball",
    softball = "softball"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEquipmentItem(item: EquipmentItem): Promise<EquipmentItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createIssuance(issuance: Issuance): Promise<Issuance>;
    deleteEquipmentItem(id: bigint): Promise<void>;
    deleteUser(id: bigint): Promise<void>;
    getActiveIssuances(): Promise<Array<Issuance>>;
    getAllEquipmentItems(sport: Sport | null): Promise<Array<EquipmentItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEquipmentItem(id: bigint): Promise<EquipmentItem>;
    getIssuanceHistoryForItem(equipmentItemId: bigint): Promise<Array<Issuance>>;
    getIssuancesByRecipient(recipientName: string): Promise<Array<Issuance>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listUsers(): Promise<Array<User>>;
    loginUser(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markAsReturned(issuanceId: bigint, returnCondition: EquipmentCondition): Promise<Issuance>;
    registerUser(name: string, email: string, password: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEquipmentItem(id: bigint, item: EquipmentItem): Promise<EquipmentItem>;
}
import type { EquipmentCategory as _EquipmentCategory, EquipmentCondition as _EquipmentCondition, EquipmentItem as _EquipmentItem, Issuance as _Issuance, RecipientType as _RecipientType, Sport as _Sport, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEquipmentItem(arg0: EquipmentItem): Promise<EquipmentItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipmentItem(to_candid_EquipmentItem_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipmentItem(to_candid_EquipmentItem_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createIssuance(arg0: Issuance): Promise<Issuance> {
        if (this.processError) {
            try {
                const result = await this.actor.createIssuance(to_candid_Issuance_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Issuance_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIssuance(to_candid_Issuance_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Issuance_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEquipmentItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipmentItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipmentItem(arg0);
            return result;
        }
    }
    async deleteUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getActiveIssuances(): Promise<Array<Issuance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveIssuances();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveIssuances();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEquipmentItems(arg0: Sport | null): Promise<Array<EquipmentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipmentItems(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipmentItems(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipmentItem(arg0: bigint): Promise<EquipmentItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentItem(arg0);
                return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentItem(arg0);
            return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIssuanceHistoryForItem(arg0: bigint): Promise<Array<Issuance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIssuanceHistoryForItem(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIssuanceHistoryForItem(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIssuancesByRecipient(arg0: string): Promise<Array<Issuance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIssuancesByRecipient(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIssuancesByRecipient(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAsReturned(arg0: bigint, arg1: EquipmentCondition): Promise<Issuance> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsReturned(arg0, to_candid_EquipmentCondition_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Issuance_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsReturned(arg0, to_candid_EquipmentCondition_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Issuance_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEquipmentItem(arg0: bigint, arg1: EquipmentItem): Promise<EquipmentItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipmentItem(arg0, to_candid_EquipmentItem_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipmentItem(arg0, to_candid_EquipmentItem_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_EquipmentItem_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EquipmentCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentCategory): EquipmentCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentCondition_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentCondition): EquipmentCondition {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentItem_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentItem): EquipmentItem {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Issuance_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Issuance): Issuance {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RecipientType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipientType): RecipientType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EquipmentCondition]): EquipmentCondition | null {
    return value.length === 0 ? null : from_candid_EquipmentCondition_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    availableQuantity: bigint;
    name: string;
    sport: _Sport;
    notes: string;
    category: _EquipmentCategory;
    totalQuantity: bigint;
    condition: _EquipmentCondition;
}): {
    id: bigint;
    availableQuantity: bigint;
    name: string;
    sport: Sport;
    notes: string;
    category: EquipmentCategory;
    totalQuantity: bigint;
    condition: EquipmentCondition;
} {
    return {
        id: value.id,
        availableQuantity: value.availableQuantity,
        name: value.name,
        sport: from_candid_Sport_n11(_uploadFile, _downloadFile, value.sport),
        notes: value.notes,
        category: from_candid_EquipmentCategory_n13(_uploadFile, _downloadFile, value.category),
        totalQuantity: value.totalQuantity,
        condition: from_candid_EquipmentCondition_n15(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: bigint;
    quantityIssued: bigint;
    recipientPhone: string;
    isReturned: boolean;
    returnCondition: [] | [_EquipmentCondition];
    notes: string;
    equipmentItemId: bigint;
    recipientName: string;
    recipientType: _RecipientType;
    returnDate: [] | [bigint];
    recipientEmail: string;
}): {
    id: bigint;
    issueDate: bigint;
    quantityIssued: bigint;
    recipientPhone: string;
    isReturned: boolean;
    returnCondition?: EquipmentCondition;
    notes: string;
    equipmentItemId: bigint;
    recipientName: string;
    recipientType: RecipientType;
    returnDate?: bigint;
    recipientEmail: string;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        quantityIssued: value.quantityIssued,
        recipientPhone: value.recipientPhone,
        isReturned: value.isReturned,
        returnCondition: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.returnCondition)),
        notes: value.notes,
        equipmentItemId: value.equipmentItemId,
        recipientName: value.recipientName,
        recipientType: from_candid_RecipientType_n26(_uploadFile, _downloadFile, value.recipientType),
        returnDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.returnDate)),
        recipientEmail: value.recipientEmail
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    baseball: null;
} | {
    softball: null;
}): Sport {
    return "baseball" in value ? Sport.baseball : "softball" in value ? Sport.softball : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bat: null;
} | {
    tee: null;
} | {
    helmet: null;
} | {
    chestPlate: null;
} | {
    baseball: null;
} | {
    catchersHelmet: null;
} | {
    other: null;
} | {
    shinGuards: null;
} | {
    softball: null;
} | {
    catchersGlove: null;
} | {
    glove: null;
} | {
    equipmentBag: null;
}): EquipmentCategory {
    return "bat" in value ? EquipmentCategory.bat : "tee" in value ? EquipmentCategory.tee : "helmet" in value ? EquipmentCategory.helmet : "chestPlate" in value ? EquipmentCategory.chestPlate : "baseball" in value ? EquipmentCategory.baseball : "catchersHelmet" in value ? EquipmentCategory.catchersHelmet : "other" in value ? EquipmentCategory.other : "shinGuards" in value ? EquipmentCategory.shinGuards : "softball" in value ? EquipmentCategory.softball : "catchersGlove" in value ? EquipmentCategory.catchersGlove : "glove" in value ? EquipmentCategory.glove : "equipmentBag" in value ? EquipmentCategory.equipmentBag : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    damaged: null;
} | {
    fair: null;
} | {
    good: null;
}): EquipmentCondition {
    return "damaged" in value ? EquipmentCondition.damaged : "fair" in value ? EquipmentCondition.fair : "good" in value ? EquipmentCondition.good : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coach: null;
} | {
    team: null;
}): RecipientType {
    return "coach" in value ? RecipientType.coach : "team" in value ? RecipientType.team : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Issuance>): Array<Issuance> {
    return value.map((x)=>from_candid_Issuance_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EquipmentItem>): Array<EquipmentItem> {
    return value.map((x)=>from_candid_EquipmentItem_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EquipmentCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentCategory): _EquipmentCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentCondition_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentCondition): _EquipmentCondition {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentItem_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentItem): _EquipmentItem {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Issuance_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Issuance): _Issuance {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_RecipientType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientType): _RecipientType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport | null): [] | [_Sport] {
    return value === null ? candid_none() : candid_some(to_candid_Sport_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    availableQuantity: bigint;
    name: string;
    sport: Sport;
    notes: string;
    category: EquipmentCategory;
    totalQuantity: bigint;
    condition: EquipmentCondition;
}): {
    id: bigint;
    availableQuantity: bigint;
    name: string;
    sport: _Sport;
    notes: string;
    category: _EquipmentCategory;
    totalQuantity: bigint;
    condition: _EquipmentCondition;
} {
    return {
        id: value.id,
        availableQuantity: value.availableQuantity,
        name: value.name,
        sport: to_candid_Sport_n3(_uploadFile, _downloadFile, value.sport),
        notes: value.notes,
        category: to_candid_EquipmentCategory_n5(_uploadFile, _downloadFile, value.category),
        totalQuantity: value.totalQuantity,
        condition: to_candid_EquipmentCondition_n7(_uploadFile, _downloadFile, value.condition)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: bigint;
    quantityIssued: bigint;
    recipientPhone: string;
    isReturned: boolean;
    returnCondition?: EquipmentCondition;
    notes: string;
    equipmentItemId: bigint;
    recipientName: string;
    recipientType: RecipientType;
    returnDate?: bigint;
    recipientEmail: string;
}): {
    id: bigint;
    issueDate: bigint;
    quantityIssued: bigint;
    recipientPhone: string;
    isReturned: boolean;
    returnCondition: [] | [_EquipmentCondition];
    notes: string;
    equipmentItemId: bigint;
    recipientName: string;
    recipientType: _RecipientType;
    returnDate: [] | [bigint];
    recipientEmail: string;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        quantityIssued: value.quantityIssued,
        recipientPhone: value.recipientPhone,
        isReturned: value.isReturned,
        returnCondition: value.returnCondition ? candid_some(to_candid_EquipmentCondition_n7(_uploadFile, _downloadFile, value.returnCondition)) : candid_none(),
        notes: value.notes,
        equipmentItemId: value.equipmentItemId,
        recipientName: value.recipientName,
        recipientType: to_candid_RecipientType_n21(_uploadFile, _downloadFile, value.recipientType),
        returnDate: value.returnDate ? candid_some(value.returnDate) : candid_none(),
        recipientEmail: value.recipientEmail
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientType): {
    coach: null;
} | {
    team: null;
} {
    return value == RecipientType.coach ? {
        coach: null
    } : value == RecipientType.team ? {
        team: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    baseball: null;
} | {
    softball: null;
} {
    return value == Sport.baseball ? {
        baseball: null
    } : value == Sport.softball ? {
        softball: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentCategory): {
    bat: null;
} | {
    tee: null;
} | {
    helmet: null;
} | {
    chestPlate: null;
} | {
    baseball: null;
} | {
    catchersHelmet: null;
} | {
    other: null;
} | {
    shinGuards: null;
} | {
    softball: null;
} | {
    catchersGlove: null;
} | {
    glove: null;
} | {
    equipmentBag: null;
} {
    return value == EquipmentCategory.bat ? {
        bat: null
    } : value == EquipmentCategory.tee ? {
        tee: null
    } : value == EquipmentCategory.helmet ? {
        helmet: null
    } : value == EquipmentCategory.chestPlate ? {
        chestPlate: null
    } : value == EquipmentCategory.baseball ? {
        baseball: null
    } : value == EquipmentCategory.catchersHelmet ? {
        catchersHelmet: null
    } : value == EquipmentCategory.other ? {
        other: null
    } : value == EquipmentCategory.shinGuards ? {
        shinGuards: null
    } : value == EquipmentCategory.softball ? {
        softball: null
    } : value == EquipmentCategory.catchersGlove ? {
        catchersGlove: null
    } : value == EquipmentCategory.glove ? {
        glove: null
    } : value == EquipmentCategory.equipmentBag ? {
        equipmentBag: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentCondition): {
    damaged: null;
} | {
    fair: null;
} | {
    good: null;
} {
    return value == EquipmentCondition.damaged ? {
        damaged: null
    } : value == EquipmentCondition.fair ? {
        fair: null
    } : value == EquipmentCondition.good ? {
        good: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
